const validarData=s=>/^\d{4}-\d{2}-\d{2}$/.test(String(s||''));
const validarHora=s=>!s||/^([01]\d|2[0-3]):[0-5]\d$/.test(String(s));

module.exports=function registrarEstudos(app,pool,exigirLogin){
  const garantir=async()=>{
    await pool.query(`CREATE TABLE IF NOT EXISTS materias_estudo (id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL, nome TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(usuario_id,nome))`);
    await pool.query(`CREATE TABLE IF NOT EXISTS conteudos_estudo (id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL, materia_id INTEGER NOT NULL, titulo TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'nao-iniciado' CHECK(status IN ('nao-iniciado','estudando','aprendido')), criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(), atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await pool.query(`CREATE TABLE IF NOT EXISTS sessoes_estudo (id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL, materia_id INTEGER NOT NULL, conteudo_id INTEGER, data TEXT NOT NULL, hora_inicio TEXT, hora_fim TEXT, duracao_planejada INTEGER NOT NULL DEFAULT 0, duracao_real INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'planejada' CHECK(status IN ('planejada','concluida','cancelada')), observacao TEXT NOT NULL DEFAULT '', criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  };
  const usuario=req=>req.session?.usuario?.id ?? req.session?.usuario_id;
  app.get('/api/estudos',exigirLogin,async(req,res)=>{try{await garantir();const u=usuario(req);const [m,c,s]=await Promise.all([pool.query('SELECT * FROM materias_estudo WHERE usuario_id=$1 ORDER BY nome',[u]),pool.query('SELECT * FROM conteudos_estudo WHERE usuario_id=$1 ORDER BY criado_em DESC',[u]),pool.query('SELECT * FROM sessoes_estudo WHERE usuario_id=$1 ORDER BY data DESC,hora_inicio DESC NULLS LAST,id DESC',[u])]);res.json({sucesso:true,materias:m.rows,conteudos:c.rows,sessoes:s.rows})}catch(e){console.error(e);res.status(500).json({sucesso:false,mensagem:'Erro interno do servidor.'})}});
  app.post('/api/estudos/materias',exigirLogin,async(req,res)=>{try{await garantir();const u=usuario(req),nome=String(req.body.nome||'').trim(),descricao=String(req.body.descricao||'').trim();if(!nome||nome.length>80)return res.status(400).json({sucesso:false,mensagem:'Informe uma matéria válida.'});const r=await pool.query('INSERT INTO materias_estudo(usuario_id,nome,descricao) VALUES($1,$2,$3) RETURNING *',[u,nome,descricao]);res.json({sucesso:true,materia:r.rows[0]})}catch(e){res.status(e.code==='23505'?400:500).json({sucesso:false,mensagem:e.code==='23505'?'Essa matéria já existe.':'Não foi possível criar a matéria.'})}});
  app.put('/api/estudos/materias/:id',exigirLogin,async(req,res)=>{try{const u=usuario(req),id=Number(req.params.id),nome=String(req.body.nome||'').trim(),descricao=String(req.body.descricao||'').trim();if(!id||!nome||nome.length>80)return res.status(400).json({sucesso:false,mensagem:'Dados inválidos.'});const r=await pool.query('UPDATE materias_estudo SET nome=$1,descricao=$2 WHERE id=$3 AND usuario_id=$4 RETURNING *',[nome,descricao,id,u]);if(!r.rowCount)return res.status(404).json({sucesso:false,mensagem:'Matéria não encontrada.'});res.json({sucesso:true,materia:r.rows[0]})}catch(e){res.status(e.code==='23505'?400:500).json({sucesso:false,mensagem:'Não foi possível atualizar a matéria.'})}});
  app.delete('/api/estudos/materias/:id',exigirLogin,async(req,res)=>{try{const u=usuario(req),id=Number(req.params.id);await pool.query('DELETE FROM conteudos_estudo WHERE materia_id=$1 AND usuario_id=$2',[id,u]);await pool.query('DELETE FROM sessoes_estudo WHERE materia_id=$1 AND usuario_id=$2',[id,u]);const r=await pool.query('DELETE FROM materias_estudo WHERE id=$1 AND usuario_id=$2',[id,u]);res.json({sucesso:!!r.rowCount})}catch(e){res.status(500).json({sucesso:false,mensagem:'Não foi possível excluir a matéria.'})}});
  app.post('/api/estudos/conteudos',exigirLogin,async(req,res)=>{try{const u=usuario(req),materia=Number(req.body.materia_id),titulo=String(req.body.titulo||'').trim(),status=String(req.body.status||'nao-iniciado');if(!materia||!titulo||titulo.length>120||!['nao-iniciado','estudando','aprendido'].includes(status))return res.status(400).json({sucesso:false,mensagem:'Dados inválidos.'});const ok=await pool.query('SELECT 1 FROM materias_estudo WHERE id=$1 AND usuario_id=$2',[materia,u]);if(!ok.rowCount)return res.status(404).json({sucesso:false,mensagem:'Matéria não encontrada.'});const r=await pool.query('INSERT INTO conteudos_estudo(usuario_id,materia_id,titulo,status) VALUES($1,$2,$3,$4) RETURNING *',[u,materia,titulo,status]);res.json({sucesso:true,conteudo:r.rows[0]})}catch(e){res.status(500).json({sucesso:false,mensagem:'Não foi possível criar o conteúdo.'})}});
  app.put('/api/estudos/conteudos/:id',exigirLogin,async(req,res)=>{try{const u=usuario(req),id=Number(req.params.id),titulo=String(req.body.titulo||'').trim(),status=String(req.body.status||'nao-iniciado');if(!id||!titulo||!['nao-iniciado','estudando','aprendido'].includes(status))return res.status(400).json({sucesso:false,mensagem:'Dados inválidos.'});const r=await pool.query('UPDATE conteudos_estudo SET titulo=$1,status=$2,atualizado_em=NOW() WHERE id=$3 AND usuario_id=$4 RETURNING *',[titulo,status,id,u]);if(!r.rowCount)return res.status(404).json({sucesso:false,mensagem:'Conteúdo não encontrado.'});res.json({sucesso:true,conteudo:r.rows[0]})}catch(e){res.status(500).json({sucesso:false,mensagem:'Não foi possível atualizar o conteúdo.'})}});
  app.delete('/api/estudos/conteudos/:id',exigirLogin,async(req,res)=>{try{const r=await pool.query('DELETE FROM conteudos_estudo WHERE id=$1 AND usuario_id=$2',[Number(req.params.id),usuario(req)]);res.json({sucesso:!!r.rowCount})}catch(e){res.status(500).json({sucesso:false,mensagem:'Não foi possível excluir o conteúdo.'})}});
  app.post('/api/estudos/sessoes',exigirLogin,async(req,res)=>{try{const u=usuario(req),materia=Number(req.body.materia_id),conteudo=req.body.conteudo_id?Number(req.body.conteudo_id):null,data=String(req.body.data||''),hi=String(req.body.hora_inicio||''),hf=String(req.body.hora_fim||''),planejada=Math.max(0,Number(req.body.duracao_planejada)||0),obs=String(req.body.observacao||'').trim();if(!materia||!validarData(data)||!validarHora(hi)||!validarHora(hf)||planejada>1440)return res.status(400).json({sucesso:false,mensagem:'Verifique data, horários e duração.'});const ok=await pool.query('SELECT 1 FROM materias_estudo WHERE id=$1 AND usuario_id=$2',[materia,u]);if(!ok.rowCount)return res.status(404).json({sucesso:false,mensagem:'Matéria não encontrada.'});if(conteudo){const oc=await pool.query('SELECT 1 FROM conteudos_estudo WHERE id=$1 AND materia_id=$2 AND usuario_id=$3',[conteudo,materia,u]);if(!oc.rowCount)return res.status(400).json({sucesso:false,mensagem:'Conteúdo inválido.'})}const r=await pool.query('INSERT INTO sessoes_estudo(usuario_id,materia_id,conteudo_id,data,hora_inicio,hora_fim,duracao_planejada,observacao) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[u,materia,conteudo,data,hi||null,hf||null,planejada,obs]);res.json({sucesso:true,sessao:r.rows[0]})}catch(e){res.status(500).json({sucesso:false,mensagem:'Não foi possível criar a sessão.'})}});
  app.put('/api/estudos/sessoes/:id',exigirLogin,async(req,res)=>{try{const u=usuario(req),id=Number(req.params.id),status=String(req.body.status||'planejada'),real=Math.max(0,Number(req.body.duracao_real)||0),obs=String(req.body.observacao||'').trim();if(!id||!['planejada','concluida','cancelada'].includes(status)||real>1440)return res.status(400).json({sucesso:false,mensagem:'Dados inválidos.'});const r=await pool.query('UPDATE sessoes_estudo SET status=$1,duracao_real=$2,observacao=$3 WHERE id=$4 AND usuario_id=$5 RETURNING *',[status,real,obs,id,u]);if(!r.rowCount)return res.status(404).json({sucesso:false,mensagem:'Sessão não encontrada.'});res.json({sucesso:true,sessao:r.rows[0]})}catch(e){res.status(500).json({sucesso:false,mensagem:'Não foi possível atualizar a sessão.'})}});
  app.delete('/api/estudos/sessoes/:id',exigirLogin,async(req,res)=>{try{const r=await pool.query('DELETE FROM sessoes_estudo WHERE id=$1 AND usuario_id=$2',[Number(req.params.id),usuario(req)]);res.json({sucesso:!!r.rowCount})}catch(e){res.status(500).json({sucesso:false,mensagem:'Não foi possível excluir a sessão.'})}});
};